from .kd import KDDistiller
from .hint import *
from .attention import AttentionDistiller
from .nst import NSTDistiller
from .sp import SPDistiller
from .rkd import RKDDistiller
from .pkt import PKTDistiller
from .svd import SVDDistiller
from .cc import *
from .vid import *