dataset:
    name: cifar10
    root: ./data/CIFAR10
    img_w: 64
    img_h: 64

training:
    optimizer:
        name: SGD
        lr: 0.05
        weight_decay: 5.0e-4
        momentum: 0.9

    lr_decay_epochs: [150, 180, 210]
    lr_decay_rate: 0.1
    batch_size: 64
    num_workers: 8
    epochs: 240
    init_epoch: 30
    seed: 1029
    save_ep_freq: 1
    print_iter_freq: 10

validation:
    batch_size: 128
    num_workers: 8

model:
    name: ResNet50
